name: macOS QEMU Test

on:
  push:

jobs:
  qemu-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install QEMU
        run: |
          brew install qemu

      - name: Check QEMU
        run: |
          qemu-system-x86_64 --version

      - name: Create test disk
        run: |
          qemu-img create -f qcow2 test.img 2G

      - name: Start QEMU with OpenGL
        run: |
          qemu-system-x86_64 \
            -m 2048 \
            -display cocoa,gl=on \
            -device virtio-vga-gl \
            -drive file=test.img,format=qcow2 &
          
          sleep 10
          
          ps aux | grep qemu
